programming_categories = [
    "Algorithms",
    "Android Development",
    "Angular",
    "Artificial Intelligence",
    "ASP.NET",
    "Assembly Language",
    "Augmented Reality",
    "AWS",
    "Azure",
    "Big Data",
    "Blockchain",
    "C++",
    "C#",
    "Cloud Computing",
    "Computer Vision",
    "Cybersecurity",
    "Data Analysis",
    "Data Mining",
    "Data Science",
    "Data Structures",
    "Database Management",
    "Deep Learning",
    "DevOps",
    "Django",
    "Docker",
    "Embedded Systems",
    "Express.js",
    "Flask",
    "Front-end Development",
    "Full-stack Development",
    "Game Development",
    "Git",
    "Go",
    "Graph Database",
    "Hadoop",
    "HTML/CSS",
    "iOS Development",
    "IoT",
    "Java",
    "JavaScript",
    "Jenkins",
    "Kubernetes",
    "Laravel",
    "Machine Learning",
    "MATLAB",
    "Microservices",
    "MongoDB",
    "MySQL",
    "Natural Language Processing",
    "Network Security",
    "Neural Networks",
    "Node.js",
    "NoSQL",
    "Object-oriented Programming",
    "Operating Systems",
    "Oracle",
    "PHP",
    "PostgreSQL",
    "Python",
    "React",
    "React Native",
    "Redis",
    "Ruby on Rails",
    "Rust",
    "Scala",
    "Serverless Computing",
    "Software Engineering",
    "Spark",
    "Spring Boot",
    "SQL",
    "Swift",
    "TensorFlow",
    "TypeScript",
    "Unity",
    "Unix",
    "Vue.js",
    "Web Development",
    "Web Services",
    "Windows",
    "Xamarin",
    "XML",
    "YAML",
]

# Add more categories to reach 100
more_categories = [
    "Agile Methodologies",
    "API Design",
    "Architecture",
    "Automated Testing",
    "Bioinformatics",
    "Business Intelligence",
    "Cloud Architecture",
    "Cloud Security",
    "Code Review",
    "Computer Graphics",
    "Computer Networks",
    "Concurrency",
    "Continuous Integration",
    "Continuous Monitoring",
    "Cryptography",
    "Data Architecture",
    "Data Governance",
    "Data Quality",
    "Database Administration",
    "Database Design",
    "DevSecOps",
    "Digital Forensics",
    "E-commerce Development",
    "Elasticsearch",
    "Enterprise Software",
    "ERP Systems",
    "Functional Programming",
    "Geographic Information Systems",
    "Graph Theory",
    "Human-Computer Interaction",
    "Image Processing",
    "Information Security",
    "Infrastructure as Code",
    "IT Project Management",
    "JavaFX",
    "JUnit",
    "Kotlin",
    "Lambda Architecture",
    "Linux Administration",
    "Load Balancing",
    "Machine Vision",
    "Microcontrollers",
    "Microsoft Azure",
    "Model-View-Controller",
    "Network Administration",
    "Network Protocols",
    "Neural Network Architectures",
]

programming_categories.extend(more_categories)
