# Generated by Django 4.2 on 2024-08-27 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='categories',
            field=models.ManyToManyField(null=True, related_name='blog_posts', to='blogpost.category'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='comments',
            field=models.ManyToManyField(null=True, related_name='blog_posts', to='blogpost.comment'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='tags',
            field=models.ManyToManyField(null=True, related_name='blog_posts', to='blogpost.tag'),
        ),
    ]
