# Generated by Django 4.2 on 2024-08-28 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0002_alter_blogmodel_categories_alter_blogmodel_comments_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='author_id',
        ),
    ]
